### PR TITLE
Deadlocks and races

### PR DESCRIPTION
**Pull request by guyer**
Fix a number of deadlock and race conditions that have made it nigh impossible to troubleshoot parallel for quite some time.

Some test failures remain, but they are not deadlock or race conditions (many fail in serial, too)

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/fipy/524)

### CODE REVIEW

**Comment by wd15** [comment]
Running `python setup.py test` gives me

---
======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid2D)
Doctest: fipy.meshes.gmshMesh.GmshGrid2D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid2D._test
  File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2188, in _test

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2199, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2202, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    yogmsh.cellCenters.value.size == yogrid.cellCenters.value.size # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2207, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    mesh.numberOfCells == 4 # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2210, in fipy.meshes.gmshMesh.GmshGrid2D._test
Failed example:
    len(mesh.faceCenters[0]) == 12 # doctest: +GMSH
Expected:
    True
Got:
    False


======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid3D)
Doctest: fipy.meshes.gmshMesh.GmshGrid3D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid3D._test
  File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2262, in _test

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2276, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    yogmsh.cellCenters.value.size == yogrid.cellCenters.value.size # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2279, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2282, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2291, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    len(mesh.cellCenters.value[0]) == 8 # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2298, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._faceAreas, faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2308, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._cellAreas, cellAreas) # doctest: +GMSH
Expected:
    True
Got:
    False


======================================================================
FAIL: mixedelement (examples.diffusion.explicit)
Doctest: examples.diffusion.explicit.mixedelement
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for examples.diffusion.explicit.mixedelement
  File "/home/wd15/git/fipy-project/fipy/examples/diffusion/explicit/mixedelement.py", line 6, in mixedelement

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/examples/diffusion/explicit/mixedelement.py", line 37, in examples.diffusion.explicit.mixedelement
Failed example:
    print var.allclose(answer)
Expected:
    1
Got:
    False


======================================================================
FAIL: TrenchMesh (examples.levelSet.electroChem.trenchMesh)
Doctest: examples.levelSet.electroChem.trenchMesh.TrenchMesh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for examples.levelSet.electroChem.trenchMesh.TrenchMesh
  File "/home/wd15/git/fipy-project/fipy/examples/levelSet/electroChem/trenchMesh.py", line 44, in TrenchMesh

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/examples/levelSet/electroChem/trenchMesh.py", line 63, in examples.levelSet.electroChem.trenchMesh.TrenchMesh
Failed example:
    print mesh.globalNumberOfCells - len(numerix.nonzero(mesh.electrolyteMask)[0]) # doctest: +GMSH, +SERIAL
Expected:
    150
Got:
    160


----------------------------------------------------------------------
Ran 545 tests in 118.284s

FAILED (failures=4)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Skipped 2 doctest examples because `lsmlib` must be used to run some tests
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
---

**Comment by wd15** [comment]
With `python setup.py test`:

```
======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid2D)
Doctest: fipy.meshes.gmshMesh.GmshGrid2D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid2D._test
  File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2189, in _test



======================================================================
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid3D)
Doctest: fipy.meshes.gmshMesh.GmshGrid3D._test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.meshes.gmshMesh.GmshGrid3D._test
  File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2263, in _test

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2277, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    yogmsh.cellCenters.value.size == yogrid.cellCenters.value.size # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2280, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2283, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    numerix.allclose(yogmsh._faceAreas, yogrid._faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2292, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    len(mesh.cellCenters.value[0]) == 8 # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2299, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._faceAreas, faceAreas) # doctest: +GMSH
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/fipy/meshes/gmshMesh.py", line 2309, in fipy.meshes.gmshMesh.GmshGrid3D._test
Failed example:
    nx.allclose(mesh._cellAreas, cellAreas) # doctest: +GMSH
Expected:
    True
Got:
    False


======================================================================
FAIL: mixedelement (examples.diffusion.explicit)
Doctest: examples.diffusion.explicit.mixedelement
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for examples.diffusion.explicit.mixedelement
  File "/home/wd15/git/fipy-project/fipy/examples/diffusion/explicit/mixedelement.py", line 6, in mixedelement

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/examples/diffusion/explicit/mixedelement.py", line 37, in examples.diffusion.explicit.mixedelement
Failed example:
    print var.allclose(answer)
Expected:
    1
Got:
    False


======================================================================
FAIL: TrenchMesh (examples.levelSet.electroChem.trenchMesh)
Doctest: examples.levelSet.electroChem.trenchMesh.TrenchMesh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wd15/miniconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for examples.levelSet.electroChem.trenchMesh.TrenchMesh
  File "/home/wd15/git/fipy-project/fipy/examples/levelSet/electroChem/trenchMesh.py", line 44, in TrenchMesh

----------------------------------------------------------------------
File "/home/wd15/git/fipy-project/fipy/examples/levelSet/electroChem/trenchMesh.py", line 63, in examples.levelSet.electroChem.trenchMesh.TrenchMesh
Failed example:
    print mesh.globalNumberOfCells - len(numerix.nonzero(mesh.electrolyteMask)[0]) # doctest: +GMSH, +SERIAL
Expected:
    150
Got:
    160


----------------------------------------------------------------------
Ran 544 tests in 125.407s

FAILED (failures=4)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Skipped 2 doctest examples because `lsmlib` must be used to run some tests
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by wd15** [comment]
and with `mpirun -np 2 python setup.py test`. Runs through to the end with 8 fails, see https://pastebin.com/JvkR0nft. Also seems to be running in parallel when testing with `mpirun -np 2 python examples/parallel.py`

Awesome work.

**Comment by guyer** [comment]
@wd15 thanks. I'm not worried about the failures right now; the goal was just to get the tests to run to completion.

**Comment by tkphd** [comment]
I can confirm that the tests run to completion in serial and in parallel using ```1..6``` cores on a 6-way SMP machine. The heads and tails of the output are available: https://gist.github.com/tkphd/685da76857fc0ce35aed9268ccd69f72.

Summary:

| Parallelism  | Runtime | Output Length | Failures | Duplicates |
| ------------ | ------: | ------------: | -------: | :--------: |
| Serial       | 4:52    | 1201          | 6        |            |
| mpirun -np 1 | 4:47    | 1212          | 7        |            |
| mpirun -np 2 | 4:52    | 2256          | 7        |            |
| mpirun -np 3 | 5:06    | 3470          | 7        | failures=6 |
| mpirun -np 4 | 5:03    | 4262          | 7        |            |
| mpirun -np 5 | 5:04    | 5475          | 7        | failures=6 |
| mpirun -np 6 | 5:24    | 6176          | 7        |            |

The parallel runs (using MPI) apparently print some info from each thread, which is an issue but not an error. Runs with odd numbers of processors (excepting ```-np 1```) printed an extra failure summary block, which is also an issue, but not an error; and who uses an odd number of processors anyway?
My runs completed, but none of the mpiruns exited cleanly: they threw, *e.g.*,
```
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30931,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

I'll take a look at the code, and flag any changes that stand out, but the results are a substantial improvement over the past deadlocking behavior.

**Comment by tkphd** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[fipy/meshes/gmshMesh.py, line 1804 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/524#-KvhsHhWvPptipC9rQm7:-KvhsHhWvPptipC9rQm8:b-gg95md) ([raw file](https://github.com/usnistgov/fipy/blob/dcdd606806f12727431fb14ee932fa12a81a52d0/fipy/meshes/gmshMesh.py#L1804)):*
> ```Python
>         <BLANKLINE>
> 
>         >>> f.close()
> ```

With all ranks opening ```f``` as a POSIX file, and writing to it without coordination, I would be shocked if we don't get corrupt output. This should be handled with an MPI_File command or using a loop over the number of ranks, writing one at a time. Or, gather the results on rank 0 and only write from that single rank.

That being said, it will at least not deadlock.

---

*[fipy/terms/abstractBinaryTerm.py, line 90 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/524#-KvhtjQLbDNhfenjRrOY:-KvhtjQLbDNhfenjRrOZ:b-6l3r66) ([raw file](https://github.com/usnistgov/fipy/blob/dcdd606806f12727431fb14ee932fa12a81a52d0/fipy/terms/abstractBinaryTerm.py#L90)):*
> ```Python
>         return (-self.term) + (-self.other)
> 
>     def _calcVars(self):
> ```

It's unclear what's being filtered here. Variables that belong to other ranks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/524)*

**Comment by guyer** [comment]
*[fipy/terms/abstractBinaryTerm.py, line 90 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/524#-KvhtjQLbDNhfenjRrOY:-Kvipk-3AiQ6iX7QbPH8:b-l4396t) ([raw file](https://github.com/usnistgov/fipy/blob/dcdd606806f12727431fb14ee932fa12a81a52d0/fipy/terms/abstractBinaryTerm.py#L90)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

It's unclear what's being filtered here. Variables that belong to other ranks?
</blockquote></details>

Added a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/524)*

**Pull request merged**
