### PR TITLE
Shift CI from eggs to wheels

### LINKED ISSUE #850: Switch to wheels
[eggs](https://setuptools.pypa.io/en/latest/userguide/commands.html?highlight=bdist_egg#bdist-egg-create-a-python-egg-for-the-project) and [wininst](https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html?highlight=wininst#module-distutils.command.bdist_wininst) are archaic and now we're getting [CI failures](https://dev.azure.com/guyer/FiPy/_build/results?buildId=237&view=logs&j=8723964c-c0a9-5d1c-da1f-e1c226f2952f&t=c379ce1d-824d-5cf7-7e34-8e8a1215a8ba). 

(Long past) time to [figure out](https://realpython.com/python-wheels/) [wheels](https://wheel.readthedocs.io/en/stable/).

### PR DESCRIPTION
**Pull request by guyer**
- Fixes #850
- Addresses #858

### CODE REVIEW

**Comment by guyer** [comment]
Qt failures have nothing to do with this PR. #862

**Comment by guyer** [comment]
- This PR needs to be merged carefully with #863

**Comment by wd15** [comment]
Doesn't look like there is anything I can try out or run in this PR so approving. Also can't find any problems just by browsing the diffs.

**Review by wd15 — APPROVED** [review]

**Comment by wd15** [comment]
Maybe squash some of the commits. Lot of commits for a limited number of changes.

**Comment by wd15** [comment]
Could have a single CI commit and a single documentation commit for example.

**Comment by guyer** [comment]
> Could have a single CI commit and a single documentation commit for example.

Thanks. I always squash and merge these days. I decided that the separate commits didn't really stand alone (the docs would be wrong without the CI changes and vice-versa).

**Pull request merged**
