### PR TITLE
Move trilinos tests to Py3k

### PR DESCRIPTION
**Pull request by guyer**
[Travis is having trouble with installing PyTrilinos on Python 2.7](https://travis-ci.com/github/usnistgov/fipy/jobs/499194951)

Running tests raises
```python
ImportError: Unable to load solver trilinos: No module named _ML
```

This happened [several years ago](https://github.com/conda-forge/pytrilinos-feedstock/issues/21) when an older build than available was getting installed.

The same seems to be true now, where `conda-forge/osx-64::pytrilinos-12.18.1-py27h1cf269a_0` is installed, but `conda-forge/osx-64::pytrilinos-12.18.1-py27hafa9833_3` and `conda-forge/osx-64::pytrilinos-12.18.1-py27h9a641e4_3` are both available (why are there two build 3s?).

### CODE REVIEW

**Comment by guyer** [comment]
Remaining failures are unrelated to this PR:

- TravisCI
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
- CircleCI
  - `conda2_env` [has problems](https://github.com/usnistgov/fipy/pull/795)
  - polyxtal freezes with Py3k and scipy solvers
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
- AppVeyor
  - Vtk is not installing correctly on Py3k

**Comment by guyer** [comment]
A better picture of the test status can be seen in the integration tests at #799

**Review by tkphd — APPROVED** [review]
Looks good, and all checks pass in #799. Good to go.

**Comment by guyer** [comment]
Issue #800 remains, but tests can be made to pass, sometimes

**Pull request merged**
