### PR TITLE
Issue625 setup py should not import fipy bis

### LINKED ISSUE #625: setup.py should not import fipy
[setup.py](https://github.com/usnistgov/fipy/blob/develop/setup.py#L4) imports several commands from the `fipy` package (`Efficiency_test`, `Copy_script`, `changelog`, `_TestClass`). As a result, simple commands like `python setup.py egg_info` don't work without at least some of FiPy's prerequisites, e.g., `numpy`, which is annoying, fragile, and potentially circular.

These commands should be moved either into `setup.py` or into an installation package that isn't `fipy`.

### PR DESCRIPTION
**Pull request by guyer**
Fixes #625
Supercedes #635

pylint gives 8.89/10.  Remaining complaints are stupid.

### CODE REVIEW

**Comment by guyer** [comment]
@wd15 @tkphd Unlike #638, this one is critical path. Can I get a review, please?

**Comment by wd15** [comment]
BTW, can make flake8 comply with black by adding
```
[flake8]
ignore = E731, W503
max-line-length = 88
```
to setup.cfg

**Comment by wd15** [comment]
Why not add the linters to .travis.yml at this point? Just for setup.py for now.

**Comment by guyer** [comment]
> Why not add the linters to .travis.yml at this point? Just for setup.py for now.

Added linting to circle because it's faster than travis and easier to compartmentalize

**Pull request merged**
