### PR TITLE
Issue584 viewers don't animate in jupyter notebook

### LINKED ISSUE #584: Viewers don't animate in jupyter notebook
jupyter semantics keep changing. 

Presently, it is necessary to import
```python
from IPython.display import display, clear_output
```
and then, instead of `viewer.plot()`, to invoke
```python
clear_output(wait=True)
display(viewer)
```

 - [ ] document this?
 - [ ] make `Viewer.plot()` do this automatically?

### PR DESCRIPTION
**Pull request by guyer**
Fixes #584

### CODE REVIEW

**Comment by wd15** [comment]
I tried the following in the notebook

```
import fipy as fp
mesh = fp.Grid2D(nx=2, ny=2)
var = fp.CellVariable(mesh=mesh, value=0.0)
for i in range(30):
    var[:] = mesh.x * mesh.y * i
    viewer.plot()
```

and it doesn't update. Should it?

**Comment by guyer** [comment]
@wd15: It does for me. Note that the plot doesn't actually change color, but the colorbar autoscales. If you  set `datamin` and `datamax`, you can see the plot changing, too.

Other possibilities:

- do you have `%matplotlib inline` set? I didn't need to, but maybe it matters?
- do you have anything set in your `~/.jupyter/` configs?

**Comment by guyer** [comment]
Never mind. I was testing `develop`, not this pull request. I'll troubleshoot.

**Comment by guyer** [comment]
I botched this pull request (I branched from `master` and then attempted to merge `develop` when I realized why I had conflicts). Closing and reopening a proper branch from `develop`.

**Pull request closed without merging**
