### PR TITLE
Corrected two tests

### PR DESCRIPTION
**Pull request by alfrenardi**
Two trivial issues with the test have been corrected.

### CODE REVIEW

**Comment by wd15** [comment]
Thanks for the fixes. Much appreciated.

**Comment by guyer** [comment]
These changes aren't really robust. They're appropriate for recent releases of NumPy, but the older tests used to be right.

**Comment by alfrenardi** [comment]
That may be true. Is there a standard method (at least regarding the convections used in FiPy) to deal with changes between different versions of the same library?

**Comment by guyer** [comment]
Not really. If you read through fipy/tools/numerix.py, you'll find a lot of special case code to account for how the libraries changed along the way.

**Pull request merged**
