### PR TITLE
Fixes for Python 3.12, NumPy 2.0, and SciPy 1.14

### LINKED ISSUE #997: future.standard_library breaking python 3.12 compatibility
future.standard_library imports the imp module which is gone in python 3.12.  So, future.standard_library is not really python 3.12 compatible.

[issue tracker](https://github.com/PythonCharmers/python-future/issues/625)

This means fipy breaks in python 3.12 at the import of the entire future.standard_library.  I'm thinking a work around could be, to be more selective about what parts of future are imported?

### LINKED ISSUE #1049: Numpy 2.0.0 breaks things
Running with Numpy 2.0.0 breaks things. See [fipy.log](https://github.com/user-attachments/files/15874209/fipy.log).

Test failures like this:

```
   Traceback (most recent call last):                                                                                                                                                         
      File "/nix/store/ffy6s77zhixlwvzprz5j0zj4ma8n8h2q-python3-3.11.8/lib/python3.11/doctest.py", line 1355, in __run                                                                         
        exec(compile(example.source, filename, "single",                                                                                                                                       
...                                                                                             
      File "/nix/store/4xbcd56id9azry5srn5fwh83qlin9lgb-python3-3.11.8-env/lib/python3.11/site-packages/fipy/variables/meshVariable.py", line 99, in __init__                                  
        dtype = numerix.obj2sctype(value)                                                                                                                                                      
                ^^^^^^^^^^^^^^^^^^                                                                                                                                                             
    AttributeError: module 'fipy.tools.numerix' has no attribute 'obj2sctype'
```

Versions are as follows:

python      3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 12.3.0]
fipy        3.4.4
numpy       2.0.0
pysparse    not installed
scipy       1.13.1
matplotlib  3.9.0

### PR DESCRIPTION
**Pull request by guyer**
Fixes #1049
Fixes #997

### CODE REVIEW

**Comment by wd15** [comment]
@guyer, you've broken Nix again!

**Comment by guyer** [comment]
@wd15, Nix is broken by design

**Comment by wd15** [comment]
Nix passes in #1051 with a single tweak

**Comment by wd15** [comment]
Nix runs and has some failures (see #1052) when testing this branch with updated Nix to 24.05 with Python 3.12 and Numpy 1.26.4. Latest version of release nixpkgs does not have Numpy 2.0.0, obviously.

**Comment by wd15** [comment]
You're not seeing this test failure anywhere, but on the Nix branch, right?

```
======================================================================
FAIL: CSR (fipy.matrices.scipyMatrix._ScipyMatrix)
Doctest: fipy.matrices.scipyMatrix._ScipyMatrix.CSR
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/c7ycrgwv039nqglbif98yggx211sdbcl-python3-3.12.3/lib/python3.12/doctest.py", line 2249, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.matrices.scipyMatrix._ScipyMatrix.CSR
  File "/home/wd15/git/fipy/fipy/matrices/scipyMatrix.py", line 280, in CSR

----------------------------------------------------------------------
File "/home/wd15/git/fipy/fipy/matrices/scipyMatrix.py", line 302, in fipy.matrices.scipyMatrix._ScipyMatrix.CSR
Failed example:
    print(numerix.asarray(cols))
Expected:
    [0 1 2 1 2 0 2]
Got:
    [0 2 1 2 1 2 0]
----------------------------------------------------------------------
File "/home/wd15/git/fipy/fipy/matrices/scipyMatrix.py", line 304, in fipy.matrices.scipyMatrix._ScipyMatrix.CSR
Failed example:
    print(numerix.asarray(data))
Expected:
    [ 12.3         10.           3.           3.14159265   2.96
       2.5          2.2       ]
Got:
    [ 12.3          3.          10.           2.96         3.14159265
       2.2          2.5       ]


----------------------------------------------------------------------
```

**Comment by wd15** [comment]
This is with Numpy 1.26.4 and Scipy 1.13.0.

**Comment by wd15** [comment]
@guyer, can I bring the changes from #1052 into this branch?

**Comment by guyer** [comment]
> @guyer, you're not seeing this test failure anywhere, but on the Nix branch, right?

Nope

**Comment by guyer** [comment]
> @guyer, can I bring the changes from #1052 into this branch?

@wd15, yes, please

**Review by wd15 — APPROVED** [review]

**Comment by wd15** [comment]
Next step might be to try and build a conda environment with the same numpy and scipy versions as the Nix build to see if it also fails that one test.

**Comment by guyer** [comment]
> Next step might be to try and build a conda environment with the same numpy and scipy versions as the Nix build to see if it also fails that one test.

Agreed. I built such an environment on my Mac and get the same error:
```
python      3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
fipy        3.4.4+41.ge25c210ec
numpy       1.26.4
pysparse    not installed
scipy       1.13.0
matplotlib  3.8.4
mpi4py      not installed
petsc4py    not installed
pyamgx      not installed
PyTrilinos  not installed
mayavi      4.8.2
gmsh        4.12.2
solver      scipy

 :
 :

======================================================================
FAIL: CSR (fipy.matrices.scipyMatrix._ScipyMatrix)
Doctest: fipy.matrices.scipyMatrix._ScipyMatrix.CSR
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guyer/mambaforge-arm/envs/nix-scipy/lib/python3.12/doctest.py", line 2256, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.matrices.scipyMatrix._ScipyMatrix.CSR
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/scipyMatrix.py", line 280, in CSR

----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/scipyMatrix.py", line 302, in fipy.matrices.scipyMatrix._ScipyMatrix.CSR
Failed example:
    print(numerix.asarray(cols))
Expected:
    [0 1 2 1 2 0 2]
Got:
    [0 2 1 2 1 2 0]
----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/matrices/scipyMatrix.py", line 304, in fipy.matrices.scipyMatrix._ScipyMatrix.CSR
Failed example:
    print(numerix.asarray(data))
Expected:
    [ 12.3         10.           3.           3.14159265   2.96
       2.5          2.2       ]
Got:
    [ 12.3          3.          10.           2.96         3.14159265
       2.2          2.5       ]


----------------------------------------------------------------------
Ran 541 tests in 78.140s

FAILED (failures=1)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Skipped 38 doctest examples because neither `lsmlib` nor `skfmm` can be found on the $PATH
Skipped 1 doctest examples because `skfmm` must be used to run some tests
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by guyer** [comment]
SciPy 1.13, in combination with all versions of numpy 1.26.x or numpy 2.0.0 exhibit this issue under Python 3.12 (earlier numpy not an option)

**Comment by guyer** [comment]
The issue goes away with SciPy 1.13.1, with any compatible numpy. Possibly fixed by scipy/scipy#20670.

**Comment by wd15** [comment]
> The issue goes away with SciPy 1.13.1, with any compatible numpy. Possibly fixed by [scipy/scipy#20670](https://github.com/scipy/scipy/issues/20670).

Oh, great. Let me see if I can get a newer scipy into the mix.

**Pull request merged**
