### PR TITLE
Fix broken circleSquare with newer Gmsh

### LINKED ISSUE #792: circleQuad example fails with Gmsh > 4.4
As noted in #791, examples/diffusion/circleQuad.py fails with Gmsh > 4.4.

The magnitude of the error is about three times larger with Gmsh 4.6. The cell sizes are similar, but the orthogonality is much worse:

|Gmsh 3.0.6|Gmsh 4.6.0|
|-----------|-----------|
|error_gmsh3 0 6|error_gmsh4 6 0|
|volume_gmsh3 0 6|volume_gmsh4 6 0|
|nonorthogonality_gmsh3 0 6|nonorthogonality_gmsh4 6 0|

### PR DESCRIPTION
**Pull request by guyer**
Fixes #792

### CODE REVIEW

**Comment by guyer** [comment]
Remaining failures are unrelated to issue #792:
- TravisCI
  - PyTrilinos is not installing correctly 
- CircleCI
  - `conda2_env` [has problems](https://github.com/usnistgov/fipy/pull/795)
  - [polyxtal freezes with Py3k and `scipy` solvers](https://github.com/usnistgov/fipy/issues/796)
- AppVeyor
  - Vtk is not installing correctly on Py3k

**Review by tkphd — APPROVED** [review]
Smoothing an awful lot LGTM

**Comment by guyer** [comment]
A better picture of the test status can be seen in the integration tests at #799

**Review by tkphd — APPROVED** [review]
All checks pass in #799. Looks good to go.

**Pull request merged**
