### PR TITLE
Integration branch

### PR DESCRIPTION
**Pull request by guyer**
Integrate PRs ~~#794 #795 #797 #798~~ #804 #807

### CODE REVIEW

**Review by tkphd — APPROVED** [review]
Looks sane to me.

**Comment by guyer** [comment]
Thanks @tkphd, but this PR won't ever be merged. It's just here to check the test status of a bunch of overlapping PRs.

**Comment by guyer** [comment]
- CircleCI
  - `conda2_env` is really slow and ends up installing FiPy 3.3. Often times out such that Python 2.7 tests don't get run.
  - `test-36-trilinos-serial` extremely slow. Often times out.
  - `test-36-scipy` extremely slow. Often times out.

**Comment by tkphd** [comment]
:tada: All checks gave passed! :tada:
Well done @guyer!

**Comment by guyer** [comment]
Done with integration testing

**Pull request closed without merging**
