### PR TITLE
CIs error on deprecation warning

### PR DESCRIPTION
**Pull request by guyer**
Cause `DeprecationWarning` to raise an Exception when the CIs run the tests.

Try to prevent things like #703 from sneaking up on us

### CODE REVIEW

**Comment by wd15** [comment]
This isn't working for me. If say I add 

```
import warnings

def my_func():
    """
    >>> my_func()
    """
    # warnings.simplefilter(
    #     "error",
    #     category=DeprecationWarning
    # )
    warnings.warn(
        "in my_func",
        DeprecationWarning
    )
    #raise Exception('hello')

```
near the top of `fipy/variable.py` and run `python setup.py test --deprecation-errors --modules` then I'm seeing a deprecation warning, but not an error. Is that the correct behavior. I guess we don't want it to fail on our own deprecation warnings. How does it know whether it's our own or an outside modules deprecation warning?

**Comment by wd15** [comment]
Also, we're getting `/home/wd15/git/fipy/fipy/tests/test.py:237: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.` (I'm getting). Should that fail?

**Comment by guyer** [comment]
@wd15 I saw the `PkgResourcesDeprecationWarning` at one point, but then couldn't reproduce it. Can you post a traceback?

**Comment by guyer** [comment]
Nevermind. I see, there is no traceback.

**Comment by guyer** [comment]
`PkgResourcesDeprecationWarning` both [derives from `Warning`](https://github.com/pypa/pip/blob/bd02564af265079fa0e3e6d6b9cbe39cc0fa6aff/src/pip/_vendor/pkg_resources/__init__.py#L3290), not `DeprecationWarning`, and it gets called before the tests are run. If it errored, it would just prevent the tests from running at all.

**Comment by guyer** [comment]
@wd15 I get
```python
======================================================================
FAIL: my_func (fipy.variables.variable)
Doctest: fipy.variables.variable.my_func
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/guyer/anaconda/envs/fipy/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.variables.variable.my_func
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/variable.py", line 21, in my_func

----------------------------------------------------------------------
File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/variable.py", line 23, in fipy.variables.variable.my_func
Failed example:
    my_func()
Exception raised:
    Traceback (most recent call last):
      File "/Users/guyer/anaconda/envs/fipy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest fipy.variables.variable.my_func[0]>", line 1, in <module>
        my_func()
      File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/variable.py", line 31, in my_func
        DeprecationWarning
    DeprecationWarning: in my_func


----------------------------------------------------------------------
Ran 347 tests in 18.455s

FAILED (failures=1)
```

**Comment by guyer** [comment]
@wd15 Your test case generates an error for me with Python 2.7.15, but not with Python 3.6.7

**Comment by guyer** [comment]
@wd15 I managed to get DeprecationWarning to throw on Py3k as well

**Comment by guyer** [comment]
@wd15 @tkphd :hourglass_flowing_sand:

**Pull request merged**
