### PR TITLE
Replace deprecated numpy types

### PR DESCRIPTION
**Pull request by guyer**
Recent NumPy versions (~1.20) raise a number of deprecation warnings:
- "`np.bool` is a deprecated alias for the builtin `bool`" in `fipy.variables.variable`
- "`np.int` is a deprecated alias for the builtin `int`" in `skfmm`
- "Converting `np.character` to a dtype is deprecated" in `tvtk`

### CODE REVIEW

**Comment by guyer** [comment]
Remaining failures are unrelated to this PR:

- TravisCI
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
  - PyTrilinos is not installing correctly
- CircleCI
  - `conda2_env` [has problems](https://github.com/usnistgov/fipy/pull/795)
  - polyxtal freezes with Py3k and scipy solvers
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
- AppVeyor
  - Vtk is not installing correctly on Py3k
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)

**Review by tkphd — APPROVED** [review]
Seems reasonable. I have not tested locally, but confirmed that the CI errors are unrelated. LGTM.

**Comment by guyer** [comment]
I've added more changes of the same character, although in these cases, the deprecations are not in our code, so I've silenced the errors in the tests, rather than doing anything useful to make the deprecation go away. 
- `skfmm` has already been fixed and just needs to percolate to pip. 
-`tvtk` has been fixed, but we're getting `mayavi` 4.7.1 instead of 4.7.2 for some reason. Regardless, my hope is to excise it completely in the rather short term.

**Comment by guyer** [comment]
A better picture of the test status can be seen in the integration tests at #799

**Review by tkphd — APPROVED** [review]
All checks pass in #799. Yeet those types.

**Pull request merged**
