### PR TITLE
add badges to index and readme

### PR DESCRIPTION
**Pull request by tkphd**
Addresses #538. May break PDF documentation: Sphinx warns
```
Running Sphinx v1.5.1
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
loading pickled environment... not yet created
WARNING: latex_use_parts is deprecated. Use latex_toplevel_sectioning instead.
```
and the build crashes to `pdb` after throwing
```
Traceback (most recent call last):
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/builders/latex.py", line 130, in write
    docwriter.write(doctree, destination)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/writers/latex.py", line 159, in translate
    visitor = self.translator_class(self.document, self.builder)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/writers/latex.py", line 366, in __init__
    self.sectionnames.index(builder.config.latex_toplevel_sectioning)
ValueError: 'parts' is not in list
> /users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/Sphinx-1.5.1-py2.7.egg/sphinx/writers/latex.py(366)__init__()
-> self.sectionnames.index(builder.config.latex_toplevel_sectioning)
```

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/fipy/546)

### CODE REVIEW

**Comment by guyer** [comment]
*[README.rst, line 248 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3E69KnZhcVfg8jlYSp:-L3E69KnZhcVfg8jlYSq:b-p6fqql) ([raw file](https://github.com/usnistgov/fipy/blob/c21ecd815c0bb4ed26a29496765f9b818b586949/README.rst#L248)):*
> ```reStructuredText
> .. |OpenHub|       image:: https://www.openhub.net/p/fipy/widgets/project_thin_badge.gif
> .. _OpenHub:       https://www.openhub.net/p/fipy
> .. |PyPi|          image:: https://img.shields.io/pypi/dm/FiPy.svg?style=flat
> ```

PyPI badge shows as `[downloads|no longer available]`, which seems to be due to [this decision](https://mail.python.org/pipermail/distutils-sig/2013-May/020855.html) and [issue](https://github.com/badges/shields/issues/716)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/546)*

**Comment by guyer** [comment]
*[documentation/_templates/index.html, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3FGxg1UGUirIaBrcBl:-L3FGxg1UGUirIaBrcBm:b-h9d520) ([raw file](https://github.com/usnistgov/fipy/blob/c98fd58175625a87336f381ff1dbaa0e23734b56/documentation/_templates/index.html#L1)):*
> ```HTML
> {% extends "layout.html" %}
> ```

Is there some pressing reason for breaking the whole website?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/546)*

**Comment by guyer** [comment]
*[README.rst, line 26 at r2](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3FIvCr7Q_uZSllV0tm:-L3FIvCr7Q_uZSllV0tn:b-efem75) ([raw file](https://github.com/usnistgov/fipy/blob/82da49c9173102fb4105e0b828f7d4339d55fe3a/README.rst#L26)):*
> |GitHub|_ |gitter|_ |TravisCI|_ |OpenHub|_ |CondaForge|_ |Depsy|_ |PyPi|_

This should be indented: 

`README.rst:26: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/546)*

**Comment by guyer** [comment]
Sphinx seems OK after all. I just was missing a package in my sphinx installation.  I get no build errors with sphinx v1.6.3 (but do get many warnings (#551)

**Comment by tkphd** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/_templates/index.html, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3FGxg1UGUirIaBrcBl:-L3FOjsnyJadavwXxwVE:bpumyyo) ([raw file](https://github.com/usnistgov/fipy/blob/c98fd58175625a87336f381ff1dbaa0e23734b56/documentation/_templates/index.html#L1)):*
<details><summary><i>Previously, guyer (Jonathan Guyer) wrote…</i></summary><blockquote>

Is there some pressing reason for breaking the whole website?
</blockquote></details>

Did I break it? Didn't actually build the site, not sure in what way it's broken. Or is this the wrong file to modify?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/546)*

**Comment by tkphd** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.rst, line 248 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3E69KnZhcVfg8jlYSp:-L3FPEJksDLM5N4TBYjh:b-896fix) ([raw file](https://github.com/usnistgov/fipy/blob/c21ecd815c0bb4ed26a29496765f9b818b586949/README.rst#L248)):*
<details><summary><i>Previously, guyer (Jonathan Guyer) wrote…</i></summary><blockquote>

PyPI badge shows as `[downloads|no longer available]`, which seems to be due to [this decision](https://mail.python.org/pipermail/distutils-sig/2013-May/020855.html) and [issue](https://github.com/badges/shields/issues/716)
</blockquote></details>

Done.

---

*[README.rst, line 26 at r2](https://reviewable.io:443/reviews/usnistgov/fipy/546#-L3FIvCr7Q_uZSllV0tm:-L3FPD8NAkZ_1L5cl4qy:b-896fix) ([raw file](https://github.com/usnistgov/fipy/blob/82da49c9173102fb4105e0b828f7d4339d55fe3a/README.rst#L26)):*
<details><summary><i>Previously, guyer (Jonathan Guyer) wrote…</i></summary><blockquote>

> |GitHub|_ |gitter|_ |TravisCI|_ |OpenHub|_ |CondaForge|_ |Depsy|_ |PyPi|_

This should be indented: 

`README.rst:26: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/546)*

**Comment by guyer** [comment]
OK. I'l stop tormenting you. Approved for merge.

**Comment by wd15** [comment]
I can't build the documentation right now so I'll just approve this, but I don't know that it works

I get

```
$ python setup.py build_docs --html
...
Running Sphinx v1.6.5
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
Exception occurred while building, starting debugger:
Traceback (most recent call last):
...
```
I can't figure out how to install imgmath `pip install sphinxcontrib-imgmath` doesn't work.

**Comment by wd15** [comment]
Shouldn't the Travis tests build the documentation of we don't use Readthedocs.

**Comment by tkphd** [comment]
@wd15 absolutely, opened #552 to address

**Comment by guyer** [comment]
@wd15 I don't think the imgmath warning (which I also get) has anything to do with the Exception, which I don't. Can you post the exception?

**Comment by wd15** [comment]
@guyer, I was missing "sphinxcontrib-traclinks", works when I get that.

**Comment by tkphd** [comment]
I've edited the Sphinx `conf.py` to clear the deprecation warnings, and divided the badges onto two lines roughly according to developer vs. user services.

**Comment by guyer** [comment]
Changing to `imgmath` breaks some of our math, e.g.,
```latex
! Undefined control sequence.
<argument> \split@tag \begin {split}-\abs 
                                          {\nabla \phi } = -\left |\frac {\p...
l.14 ...partial x}\right| = - 2 \abs{x}\end{split}
```

Make the following change in `conf.py`:
```diff
index f3ff3743..4231d2bf 100644
--- a/documentation/conf.py
+++ b/documentation/conf.py
@@ -323,7 +323,7 @@ latex_additional_files = ['figures/nistident_flright_vec.pdf']
 # If false, no module index is generated.
 #latex_use_modindex = True
 
-pngmath_latex_preamble = common_preamble
+imgmath_latex_preamble = common_preamble
 
 # refer to Python, NumPy, SciPy, matplotlib
 intersphinx_mapping = {
```

**Comment by guyer** [comment]
changing to `imgmath` had nothing to do with this pull request

**Pull request merged**
