### PR TITLE
Issue534 physical field mishandles compound units

### PR DESCRIPTION
**Pull request by guyer**
Fixes issue with raising dimensional quantities to a power reported in #534

### CODE REVIEW

**Comment by wd15** [comment]
Tests pass for me and looks good.

**Comment by tkphd** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[fipy/variables/binaryOperatorVariable.py, line 87 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1smFvvPDVyGY_WgC2F:-L1smFvvPDVyGY_WgC2G:bjz67iq) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/binaryOperatorVariable.py#L87)):*
> ```Python
>             if self._unit is None:
>                 try:
>                     var = self._varProxy
> ```

Apparently trivial change:
- Applies to binary operators: `**`, `*`, `/`, `%`, `+`, `-`, `//`, `/`, `<<`, `>>`, `&`, `^`, `|`, `==`
- Substitute `self._varProxy` for `self.var`
- Call `_extractUnit` on `self.op` using `var[0]` instead of `var[0]._unitAsOne`, etc.

From `operatorVariable.py`, if `valueMatters`, then `self._varProxy == self.var` (values and units preserved). Otherwise, `self._varProxy` is a list with units preserved but values set to ~the operator identity (*e.g.*, `1` for multiplication)~ `1`.

---

*[fipy/variables/operatorVariable.py, line 52 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1soIIyNuFWEQs23-hY:-L1smCtYuL8VT0CQfjxj:b-d2zkyz) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/operatorVariable.py#L52)):*
> ```Python
>                 self.valueMattersForUnit = [False for v in var]
>             else:
>                 self.valueMattersForUnit = valueMattersForUnit
> ```

Assume this *operator* does not influence how convolved units are computed.
- `op` is an operator
- `var` is the list of modifiers for `op`, e.g. the exponent of `**` or... ? What happens if you shift `<<` a dimensioned quantity?

---

*[fipy/variables/operatorVariable.py, line 222 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1stIMlf3g5_NiMx_ZA:-L1stIMlf3g5_NiMx_ZB:bkg0tvr) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/operatorVariable.py#L222)):*
> ```Python
>             Used for determining units of result without doing expensive computation"""
> 
>             return [v if valueMatters else v._unitAsOne for v, valueMatters in zip(self.var, self.valueMattersForUnit)]
> ```

If `valueMatters`, returns `v` (values and units preserved). Otherwise, returns a list with units preserved but values set to ~the operator identity (*e.g.* `1` for multiplication)~ `1`.

---

*[fipy/variables/unaryOperatorVariable.py, line 74 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1su_sv9WLq2TmltiOO:-L1su_swCUMENygHQfPS:b-yh4pey) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/unaryOperatorVariable.py#L74)):*
> ```Python
>             if self._unit is None:
>                 try:
>                     var = self._varProxy
> ```

Apparently trivial change:
- Applies to unary operators: `+`, `-`, `not`, `~`
- Substitute `self._varProxy` for `self.var`
- Call `_extractUnit` on `self.op` using `var` instead of `var._unitAsOne`.

From `operatorVariable.py`, if `valueMatters`, then `self._varProxy == self.var` (value and unit preserved). Otherwise, `self._varProxy` preserves the unit but sets the value to ~the operator identity (*e.g.*, `0` for addition)~ `1`.

---

*[fipy/variables/variable.py, line 1021 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1svjg3UO3E93RwJU6s:-L1svjg3UO3E93RwJU6t:bw15ns5) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1021)):*
> ```Python
>           - `opShape`: the shape that should result from the operation
>           - `valueMattersForUnit`: whether value of `self` should be used when determining unit,
>                                     e.g., ???
> ```

Please file an issue to backfill this example docstring.

---

*[fipy/variables/variable.py, line 1061 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1svx9b-O6bjfJfhozp:-L1svx9b-O6bjfJfhozq:bjpk20t) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1061)):*
> ```Python
> 
>     def _BinaryOperatorVariable(self, op, other, operatorClass=None, opShape=None, canInline=True, unit=None,
>                                 value0mattersForUnit=False, value1mattersForUnit=False):
> ```

Clunky syntax, easily overlooked. I guess it's OK?

---

*[fipy/variables/variable.py, line 1133 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1swMuANfz7Y5AJV0nH:-L1swMuANfz7Y5AJV0nI:b-g138gl) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1133)):*
> ```Python
>         >>> print (Variable(1, "mol/l")**3).unit
>         <PhysicalUnit mol**3/l**3>
>         """
> ```

Any reason for using the multiplicative identity instead of a less-special value? *e.g.*,
`print Variable(2, "mol/l")**3`?

---

*[fipy/variables/variable.py, line 1134 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1sx7JTjuJatdU6-MbZ:-L1sx7JTjuJatdU6-Mb_:bczf0ot) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1134)):*
> ```Python
>         <PhysicalUnit mol**3/l**3>
>         """
>         return self._BinaryOperatorVariable(lambda a,b: pow(a,b), other, value1mattersForUnit=True)
> ```

Clunky syntax, easily overlooked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/variable.py, line 1133 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1swMuANfz7Y5AJV0nH:-L1wpUHB_3HJ3WYcJfhp:b-8zd342) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1133)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Any reason for using the multiplicative identity instead of a less-special value? *e.g.*,
`print Variable(2, "mol/l")**3`?
</blockquote></details>

`print Variable(2, "mol/l")**3` would calculate the full value, which works and would generate the correct unit. This bug arises when FiPy precalculates the shape and unit of `Variable` expressions, in a possibly misguided effort to generate errors at the point of the code the user wrote rather than at some opaque later stage when the expression is evaluated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/operatorVariable.py, line 52 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1soIIyNuFWEQs23-hY:-L1wqOrth1reAYyqBdyp:b9ekxob) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/operatorVariable.py#L52)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Assume this *operator* does not influence how convolved units are computed.
- `op` is an operator
- `var` is the list of modifiers for `op`, e.g. the exponent of `**` or... ? What happens if you shift `<<` a dimensioned quantity?
</blockquote></details>

At such time as we introduce `__rshift__` and `__lshift__` operators to FiPy `Variables`, then we figure out what that means for both value and unit. Assuming that is their traditional meaning, and not C++ string stream abominations, then multiplying or dividing by powers of 2 would presumably not do anything special with the unit. Shifting by something dimensional would get the hose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/binaryOperatorVariable.py, line 87 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1smFvvPDVyGY_WgC2F:-L1wrU6eEuLImCyjr-x8:b-b5rr3c) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/binaryOperatorVariable.py#L87)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Apparently trivial change:
- Applies to binary operators: `**`, `*`, `/`, `%`, `+`, `-`, `//`, `/`, `<<`, `>>`, `&`, `^`, `|`, `==`
- Substitute `self._varProxy` for `self.var`
- Call `_extractUnit` on `self.op` using `var[0]` instead of `var[0]._unitAsOne`, etc.

From `operatorVariable.py`, if `valueMatters`, then `self._varProxy == self.var` (values and units preserved). Otherwise, `self._varProxy` is a list with units preserved but values set to ~the operator identity (*e.g.*, `1` for multiplication)~ `1`.
</blockquote></details>

`1 <unit>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/operatorVariable.py, line 222 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1stIMlf3g5_NiMx_ZA:-L1wrYycCx8nfSZnY0Sa:b-b5rr3c) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/operatorVariable.py#L222)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

If `valueMatters`, returns `v` (values and units preserved). Otherwise, returns a list with units preserved but values set to ~the operator identity (*e.g.* `1` for multiplication)~ `1`.
</blockquote></details>

`1 <unit>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/unaryOperatorVariable.py, line 74 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1su_sv9WLq2TmltiOO:-L1wrab1U-38IhqT0EQc:b-b5rr3c) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/unaryOperatorVariable.py#L74)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Apparently trivial change:
- Applies to unary operators: `+`, `-`, `not`, `~`
- Substitute `self._varProxy` for `self.var`
- Call `_extractUnit` on `self.op` using `var` instead of `var._unitAsOne`.

From `operatorVariable.py`, if `valueMatters`, then `self._varProxy == self.var` (value and unit preserved). Otherwise, `self._varProxy` preserves the unit but sets the value to ~the operator identity (*e.g.*, `0` for addition)~ `1`.
</blockquote></details>

`1 <unit>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Comment by guyer** [comment]
*[fipy/variables/variable.py, line 1021 at r1](https://reviewable.io:443/reviews/usnistgov/fipy/535#-L1svjg3UO3E93RwJU6s:-L1wrcfu4e6Ud1e5nuYs:b-8thw5q) ([raw file](https://github.com/usnistgov/fipy/blob/a3650af93de8e2cec8d8cc704c10395d65e40150/fipy/variables/variable.py#L1021)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Please file an issue to backfill this example docstring.
</blockquote></details>

Please file an issue to backfill this example docstring your own self.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/535)*

**Pull request merged**
