### PR TITLE
Fix Python 2.7 conda environment

### PR DESCRIPTION
**Pull request by wd15**
Strange miniconda2 incompatibility if conda is updated in base

### CODE REVIEW

**Comment by guyer** [comment]
Remaining failures are unrelated to this PR:

- TravisCI
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
  - PyTrilinos is not installing correctly
- CircleCI
  - polyxtal freezes with Py3k and scipy solvers
  - [circleQuad example fails with Gmsh > 4.4](https://github.com/usnistgov/fipy/issues/792)
  - PyTrilinos tests stall for some reason
- AppVeyor
  - Vtk is not installing correctly on Py3k

**Comment by guyer** [comment]
A better picture of the test status can be seen in the integration tests at #799

**Review by tkphd — APPROVED** [review]
Looks reasonable, and all checks pass in #799. Looks good to go.

**Comment by guyer** [comment]
Issue #800 remains, but tests can be made to pass, sometimes

**Pull request merged**
