### PR TITLE
Fix gmsh on windows

### PR DESCRIPTION
**Pull request by guyer**
Fix issues raised [here](https://stackoverflow.com/q/56341375/2019542), along with uninformative errors [here](https://stackoverflow.com/q/53955192/2019542) and [here](https://stackoverflow.com/q/55408364/2019542)

- [ ] Add gmsh to [fipy-feedstock](https://github.com/conda-forge/fipy-feedstock)

### CODE REVIEW

**Comment by tkphd** [comment]
Looks like the Python2.7 test has hung on [Appveyor](https://ci.appveyor.com/project/guyer/fipy/builds/25097671/job/vpar05l5qsehpn0l).

**Comment by guyer** [comment]
I  kicked appveyor in the pants. We'll see if it hangs again.

**Comment by guyer** [comment]
@tkphd @wd15 Hold off reviewing. I forgot a couple of things.

**Comment by guyer** [comment]
Please review. Windows Py3k will get sorted out on the fipy-feedstock.

**Comment by wd15** [comment]
0.7 lines of code per commit!

**Comment by wd15** [comment]
Might want to squash this one.

**Comment by wd15** [comment]
Subatomic commits!

**Comment by guyer** [comment]
Under heavy bombardment by squashons, commitons release high energy debugons and deletons, leaving behind the supermassive codons.

**Pull request merged**
