### PR TITLE
Convert integer to string in operator variable represenation

### LINKED ISSUE #961: Representation of index variables is broken
```python
>>> import fipy as fp
>>> mesh = fp.Grid2D(nx=3, ny=4)
>>> mesh.cellCenters[0]
Traceback (most recent call last):
  File ~/mambaforge-arm/envs/fipy311/lib/python3.11/site-packages/IPython/core/formatters.py:699 in __call__
    return repr(obj)
  File ~/Documents/research/FiPy/fipy/fipy/variables/operatorVariable.py:307 in __repr__
    return self._getRepresentation()
  File ~/Documents/research/FiPy/fipy/fipy/variables/operatorVariable.py:87 in _getRepresentation
    representation = self._py3kInstructions(op=self.op, style=style, argDict=argDict, id=id, freshen=freshen)
  File ~/Documents/research/FiPy/fipy/fipy/variables/operatorVariable.py:211 in _py3kInstructions
    stack.append(stack.pop(-2) + "[" + stack.pop() + "]")
TypeError: can only concatenate str (not "int") to str
```

The `stack.pop()` needs to be wrapped in `str()`, or the whole thing should use f-string formatting.

### PR DESCRIPTION
**Pull request by guyer**
Fixes #961
Addresses #1011

### CODE REVIEW

**Comment by tkphd** [comment]
I'm not pythonic enough to understand what this syntax change means. It looks like you're changing the code from taking the second element of the array, to I have no idea what the `[...]`-th element means.

**Comment by guyer** [comment]
> I'm not pythonic enough to understand what this syntax change means. It looks like you're changing the code from taking the second element of the array, to I have no idea what the `[...]`-th element means.

The test is asking for the represenation of the lazy evaluation of the second element in the array. Under Python 2.7, it returned `Variable(value=array([1, 2, 3, 4]))[index]`. (After this fix) under Python 3, it returns `Variable(value=array([1, 2, 3, 4]))[1]`. `# doctest: +ELLIPSIS` enables me to write a test that accepts either output.

The fact that humans won't know what that means is OK; this test is under `_testBinOp()` because it's not intended as documentation.

**Comment by tkphd** [comment]
> > I'm not pythonic enough to understand what this syntax change means. It looks like you're changing the code from taking the second element of the array, to I have no idea what the `[...]`-th element means.
> 
> The test is asking for the represenation of the lazy evaluation of the second element in the array. Under Python 2.7, it returned `Variable(value=array([1, 2, 3, 4]))[index]`. (After this fix) under Python 3, it returns `Variable(value=array([1, 2, 3, 4]))[1]`. `# doctest: +ELLIPSIS` enables me to write a test that accepts either output.
> 
> The fact that humans won't know what that means is OK; this test is under `_testBinOp()` because it's not intended as documentation.

Ah-ha! Cool, thank you.

**Comment by guyer** [comment]
nix is the devil

**Comment by tkphd** [comment]
> nix is the devil

and not spoken of in polite company

**Pull request merged**
