### PR TITLE
Issue561 cannot cast array data from dtypeint64 to dtypeint32 according to the rule safe

### LINKED ISSUE #561: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
Hi folks, 
My computer is Windows 10 x64 and the processor is also x64-based. 
When I tested the sample code on the website I got the following error.

<pre>Traceback (most recent call last):
  File "test.py", line 90, in <module>
    phaseEq.solve(phase, dt=dt)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\term.py", line 198, in solve
    solver = self._prepareLinearSystem(var, solver, boundaryConditions, dt)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\term.py", line 157, in _prepareLinearSystem
    buildExplicitIfOther=self._buildExplcitIfOther)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\binaryTerm.py", line 68, in _buildAndAddMatrices
    buildExplicitIfOther=buildExplicitIfOther)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\unaryTerm.py", line 99, in _buildAndAddMatrices
    diffusionGeomCoeff=diffusionGeomCoeff)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\cellTerm.py", line 163, in _buildMatrix
    self._buildMatrixNoInline_(L=L, oldArray=var.old, b=b, dt=dt, coeffVectors=coeffVectors)
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\terms\cellTerm.py", line 148, in _buildMatrixNoInline_
    L.addAt(coeffVectors['new value'].ravel() / dt, ids.ravel(), ids.swapaxes(0,1).ravel())
  File "C:\Users\me\Miniconda3\envs\py2\lib\site-packages\fipy-unknown-py2.7.egg\fipy\matrices\pysparseMatrix.py", line 246, in addAt
    self.matrix.update_add_at(vector, id1, id2)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'</pre>

This problem is similar to the problem mentioned in the link below.  
http://fipy.nist.narkive.com/fRBMPr5Q/problems-using-fipy-on-windows-7-computer
To resolve this problem, line 246 in pyparseMatrix.py has to be replaced by
`self.matrix.update_add_at(vector, id1.astype('int32'), id2.astype('int32'))`

### PR DESCRIPTION
**Pull request by guyer**
Fixes #561

### CODE REVIEW

**Comment by tkphd** [comment]
The Travis build threw an error with `--pysparse --inline`. Is this related to the change, or a coincidental error?

```
======================================================================
FAIL: _buildMatrix (fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm)
Doctest: fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm._buildMatrix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm._buildMatrix
  File "/home/travis/build/usnistgov/fipy/fipy/terms/abstractDiffusionTerm.py", line 294, in _buildMatrix
----------------------------------------------------------------------
File "/home/travis/build/usnistgov/fipy/fipy/terms/abstractDiffusionTerm.py", line 308, in fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm._buildMatrix
Failed example:
    eq.solve(v, solver=DummySolver())
Expected nothing
Got:
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules _winreg, win32api or win32con are installed.
----------------------------------------------------------------------
```

**Comment by guyer** [comment]
@tkphd Coincidental. Conda pulled a newer version of numpy this time, which provoked this nonsensical error. Why does a linux run need to read the registry to find _winreg, win32api or win32con?!?

@wd15 and I have discussed it and we'll be pulling `--inline` out of the travis runs. It's just too hard to maintain for too little gain.

**Comment by tkphd** [comment]
Gotcha. OK.

**Comment by guyer** [comment]
@tkphd I think we're safe for at least a little while

**Pull request merged**
