### PR TITLE
remove recvobj from calls to allgather, require sendobj

### LINKED ISSUE #491: globalValue raises error from mpi4py
As reported [on the mailing list](http://permalink.gmane.org/gmane.comp.python.fipy/4072), calling `var.globalValue` in parallel rasies
```python
(parallel)N103898:fipy guyer$ mpirun -np 2 python test.py --trilinos
hello from 0 out of 2
hello from 1 out of 2
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print 'hello from',fp.tools.parallel.procID,'out of',fp.tools.parallel.Nproc,p.globalValue
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print 'hello from',fp.tools.parallel.procID,'out of',fp.tools.parallel.Nproc,p.globalValue
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/cellVariable.py", line 162, in globalValue
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/cellVariable.py", line 162, in globalValue
    self.mesh._globalNonOverlappingCellIDs)
    self.mesh._globalNonOverlappingCellIDs)
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/meshVariable.py", line 152, in _getGlobalValue
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/variables/meshVariable.py", line 152, in _getGlobalValue
    globalIDs = numerix.concatenate(self.mesh.communicator.allgather(globalIDs))
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/tools/comms/mpi4pyCommWrapper.py", line 75, in allgather
    globalIDs = numerix.concatenate(self.mesh.communicator.allgather(globalIDs))
  File "/Users/guyer/Documents/research/FiPy/fipy/fipy/tools/comms/mpi4pyCommWrapper.py", line 75, in allgather
    return self.mpi4py_comm.allgather(sendobj=sendobj, recvobj=recvobj)
  File "MPI/Comm.pyx", line 1288, in mpi4py.MPI.Comm.allgather (src/mpi4py.MPI.c:109141)
    return self.mpi4py_comm.allgather(sendobj=sendobj, recvobj=recvobj)
  File "MPI/Comm.pyx", line 1288, in mpi4py.MPI.Comm.allgather (src/mpi4py.MPI.c:109141)
TypeError: allgather() got an unexpected keyword argument 'recvobj'
TypeError: allgather() got an unexpected keyword argument 'recvobj'
```

The `recvobj` argument was [removed in May 2014](https://bitbucket.org/mpi4py/mpi4py/commits/3d8503a11d320dd1c3030ec0dbce95f63b0ba602) and we apparently never noticed. It looks like we can safely delete it from our code as it was apparently never used for anything.

### PR DESCRIPTION
**Pull request by tkphd**
Fixes #491. Addresses changes in mpi4py commit 3d8503a1 (May 2014).

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/fipy/492)

### CODE REVIEW

**Comment by wd15** [comment]
@tkphd, all the tests passed in serial using `--trilinos` with the exception of 
```
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid2D)
FAIL: mixedelement (examples.diffusion.explicit)
...
FAILED (failures=4)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Skipped 2 doctest examples because `lsmlib` must be used to run some tests
Skipped 2 doctest examples because the PySparse solvers are not being used.
Skipped 83 doctest examples because the `tvtk` package cannot be imported
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Can you test in parallel? Then I'll merge it. Thanks.

**Comment by wd15** [comment]
BTW, I had issues with posting a comment with reviewable

**Comment by tkphd** [comment]
Most tests pass in serial as well (```python setup.py test --trilinos```), with 6 exceptions:
```
FAIL: __mul__ (fipy.matrices.trilinosMatrix._TrilinosMeshMatrix)
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid2D)
FAIL: _test (fipy.meshes.gmshMesh.GmshGrid3D)
FAIL: mixedelement (examples.diffusion.explicit)
FAIL: anisotropy (examples.diffusion)
FAIL: TrenchMesh (examples.levelSet.electroChem.trenchMesh)
...
----------------------------------------------------------------------
Ran 555 tests in 246.080s

FAILED (failures=6)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Skipped 1 doctest examples because `skfmm` must be used to run some tests
Skipped 2 doctest examples because the PySparse solvers are not being used.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Maybe the two additional test failures are of concern, esp. since trilinosMatrix.py does call allgather in its ```__str__``` method. Apparently the failure is due to ```v1 = CellVariable(mesh=m, value=_TrilinosIdentityMeshMatrix(mesh=m) * v0.value)``` failing, so ```v1``` doesn't exist when allclose gets called.

The test hangs in parallel (```mpirun -np 2 python setup.py test --trilinos```) on
```
_buildMatrix (fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm)
Doctest: fipy.terms.abstractDiffusionTerm._AbstractDiffusionTerm._buildMatrix ... 
```
which is not very far into the testing process.

I wrote quick checks in ```examples/parallel.py``` to test:
```
m4count = m4comm.allgather(m4comm.Get_rank())
for i in range(m4comm.Get_size()):
    assert m4count[i] == i
```
passes, as does
```
fpcount = parallelComm.allgather(parallelComm.procID)
for i in range(parallelComm.Nproc):
    assert fpcount[i] == i
```
However, ```epcount = epcomm.allgather(epcomm.MyPID())``` fails, reporting
```
Traceback (most recent call last):
  File "parallel.py", line 19, in <module>
Traceback (most recent call last):
  File "parallel.py", line 19, in <module>
        epcount = epcomm.allgather(epcomm.MyPID())
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 5245, in <lambda>
epcount = epcomm.allgather(epcomm.MyPID())
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 5245, in <lambda>
        __getattr__ = lambda self, name: _swig_getattr(self, MpiComm, name)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 126, in _swig_getattr
__getattr__ = lambda self, name: _swig_getattr(self, MpiComm, name)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 126, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 121, in _swig_getattr_nondynamic
    return _swig_getattr_nondynamic(self, class_type, name, 0)
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
  File "/users/tnk10/.conda/envs/fipyompi/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 121, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```
No idea what that's about. It looks like Epetra's PyComm doesn't support ```allgather```. They document ```GatherAll```, which does work (as ```epcount = epcomm.GatherAll(epcomm.MyPID())```) and passes the same test, but of course won't exercise the ```allgather``` in our commWrapper. No idea what's up.

Anyway, should the functioning allgather tests be written as doctests in mpi4pyCommWrapper.py?

**Comment by wd15** [comment]
Why not? Yes, right the little test you're doing as a doctest (if you want to). I a not sure what the resolution is. Do you think this is ready to merge?

**Comment by wd15** [comment]
Do we ever use Epetra's allgather anyway, so it isn't an issue, right? We use both mpi4py and Epetra as Epetra doesn't provide the full functionality we need.

**Comment by tkphd** [comment]
OK, I've updated the branch with a doctest for mpi4py allgather. If it looks OK to you, then yes, this branch is ready to merge.

**Comment by wd15** [comment]
@tkphd, checking that Revieable works

<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary>
> OK, I've updated the branch with a doctest for mpi4py allgather. If it looks OK to you, then yes, this branch is ready to merge.</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/fipy/492#-:-KH6XpTF49RBb6hPpVK8:836162544)*

**Pull request merged**
